Update nrf54l15.yml

diff --git a/.github/workflows/build_micropython_xiao_nrf54l15.yml b/.github/workflows/build_micropython_xiao_nrf54l15.yml
--- a/.github/workflows/build_micropython_xiao_nrf54l15.yml
+++ b/.github/workflows/build_micropython_xiao_nrf54l15.yml
@@ -56,11 +56,30 @@ jobs:
       - name: Build for Xiao nRF54L15
         run: |
           source zephyrproject/zephyr/zephyr-env.sh
-          pushd lib/micropython/ports/zephyr && gh pr checkout 18030 && popd
+          pushd lib/micropython/ports/zephyr
+          git fetch origin
+          git reset --hard origin/master
+          gh pr checkout 18030
+          popd
+          
+          if [ ! -d "lib/micropython/ports/zephyr" ]; then
+            echo "ERROR: Directory lib/micropython/ports/zephyr missing!"
+            ls -la lib/micropython/ports/
+            exit 1
+          fi
+
           export PROJECT_DIR=$(pwd)
-          west build ./lib/micropython/ports/zephyr --pristine --board xiao_nrf54l15/nrf54l15/cpuapp --sysbuild --   -DBOARD_ROOT=$PROJECT_DIR/   -DEXTRA_DTC_OVERLAY_FILE=$PROJECT_DIR/boards/xiao_nrf54l15_nrf54l15_cpuapp.overlay  -DPM_STATIC_YML_FILE=$PROJECT_DIR/boards/pm_static_xiao_nrf54l15_nrf54l15_cpuapp.yml  -DEXTRA_CONF_FILE=$PROJECT_DIR/boards/xiao_nrf54l15_nrf54l15_cpuapp.conf
-        env:
-          ZEPHYR_SDK_INSTALL_DIR: ~/zephyr-sdk/zephyr-sdk-0.17.0
+          west build ./lib/micropython/ports/zephyr \
+            --pristine \
+            --board xiao_nrf54l15/nrf54l15/cpuapp \
+            --sysbuild \
+            -- \
+            -DBOARD_ROOT=$PROJECT_DIR/ \
+            -DEXTRA_DTC_OVERLAY_FILE=$PROJECT_DIR/boards/xiao_nrf54l15_nrf54l15_cpuapp.overlay \
+            -DPM_STATIC_YML_FILE=$PROJECT_DIR/boards/pm_static_xiao_nrf54l15_nrf54l15_cpuapp.yml \
+            -DEXTRA_CONF_FILE=$PROJECT_DIR/boards/xiao_nrf54l15_nrf54l15_cpuapp.conf
+              env:
+                ZEPHYR_SDK_INSTALL_DIR: ~/zephyr-sdk/zephyr-sdk-0.17.0
 
       # Upload Xiao nRF54L15 firmware artifacts
       - name: Upload Xiao nRF54L15 artifacts
